// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLsdO525IxfzEgF7tn2KoAbUirn1eCAzQ',
    appId: '1:622439068991:web:3f3322b6236bfbc2c5cf8a',
    messagingSenderId: '622439068991',
    projectId: 'e-commerce-82fbb',
    authDomain: 'e-commerce-82fbb.firebaseapp.com',
    storageBucket: 'e-commerce-82fbb.appspot.com',
    measurementId: 'G-MKXSM2VB8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJgNupuEqhyYV92Vm3DEoRDsjrx0UDTZc',
    appId: '1:622439068991:android:800cc63c26a057c6c5cf8a',
    messagingSenderId: '622439068991',
    projectId: 'e-commerce-82fbb',
    storageBucket: 'e-commerce-82fbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5e3cIBhzijgqLYr9VVZatN9VKIuSeuLE',
    appId: '1:622439068991:ios:3384de94e2817366c5cf8a',
    messagingSenderId: '622439068991',
    projectId: 'e-commerce-82fbb',
    storageBucket: 'e-commerce-82fbb.appspot.com',
    iosBundleId: 'com.example.projectEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5e3cIBhzijgqLYr9VVZatN9VKIuSeuLE',
    appId: '1:622439068991:ios:b063b28b0975de1ec5cf8a',
    messagingSenderId: '622439068991',
    projectId: 'e-commerce-82fbb',
    storageBucket: 'e-commerce-82fbb.appspot.com',
    iosBundleId: 'com.example.projectEcommerce.RunnerTests',
  );
}
